package /* TODO package */;

import java.util.ArrayList;
import java.util.List;

public class PastaList
{
    public static List<Pasta> getPasta()
    {
        List<Pasta> list = new ArrayList<Pasta>();

        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Bigoi_co_l%27arna_%28cropped%29.jpg", "Bigoli") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Bucatinicloseup.JPG", "Bucatini") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Capellini.jpg", "Capellini") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Pistacchio_di_Bronte_%28pesto%29_-_cropped.jpg", "Fusilli") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Fusilli_lunghi_bucati.jpg", "Fusilli bucati") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Perciatelli.jpg", "Perciatelli") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Pici_con_albume.jpeg", "Pici") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Spaghetti-prepared.jpg", "Spaghetti") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Spaghettiniphoto.jpg", "Spaghettini") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Spaghettoni.jpg", "Spaghettoni") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Baked_Ziti_%28cropped%29.jpg", "Ziti") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Bavette_pasta.jpg", "Bavette") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Fettucine1.JPG", "Fettuccine") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Lasagne_Bl%C3%A4tter01.jpg", "Lasagne (Gravagna)") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Lasagnette-with-pumpkin-and-parmesan.jpg", "Lasagnette") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Linguine.jpg", "Linguine") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Mafaldine.JPG", "Mafaldine") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Pappardelle_Tomato_Sauce.jpg", "Pappardelle") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Pizzoccheri.JPG", "Pizzoccheri") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Spaghetti_alla_chitarra.jpg", "Spaghetti alla chitarra") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Stringozzi.jpg", "Stringozzi") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Picture_246_w.jpg", "Tagliatelle") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Trenette_con_le_vongole_%28cropped%29.jpg", "Trenette") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Cannelloni.jpg", "Cannelloni") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Pasta_with_pesto.jpg", "Cavatappi") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Cellentani.jpg", "Cellentani") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Pasta_e_fagioli_rapida.jpg", "Ditalini") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Fideua.jpg", "Fideua") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Pastasorten_Garganelli.JPG", "Garganelli") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Gemelli.jpg", "Gemelli") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Macaroni_closeup.jpg", "Macaroni") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-EMS-109321-Manicotti-rule..JPG", "Manicotti") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-EMS-Mostaccioli-CU-125055.JPG", "Mostaccioli") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Paccheri_pasta.jpg", "Paccheri") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Penne_with_sauce.jpg", "Penne") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Whole_wheat_penne%2C_cooked_and_uncooked.jpg", "Penne rigate") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Mezzi_Rigatoni_pasta.jpg", "Rigatoni") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Fusilli_pasta.jpg", "Rotini") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Sagne_ncannulate_pomodoro.jpg", "Sagne 'ncannulate") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-PastasortenTortiglioni.JPG", "Tortiglioni") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Campanelle_with_Summer_Veggies_%28top_view%29.jpg", "Campanelle") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Capunti.jpg", "Capunti") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Casarecce.jpg", "Casarecce") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Cavatelli_in_cheese_sauce.jpg", "Cavatelli") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Cencioni.jpg", "Cencioni") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Conchiglie_%28pasta%29.jpg", "Conchiglie") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Conchiglioni.jpg", "Conchiglioni") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Corzetti.jpg", "Corzetti") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Pasta_creste_di_galli.jpg", "Creste di galli") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Croxetti.jpg", "Croxetti") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Farfalle_Pasta.JPG", "Farfalle") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Farfalloni.jpg", "Farfalloni") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Fiorentine.jpg", "Fiorentine") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Fiori_pasta.jpg", "Fiori") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Foglie_d%27ulivo.JPG", "Foglie d'ulivo") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Gigli_pasta.jpg", "Gigli") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Gramigna.jpg", "Gramigna") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Lanterne.jpg", "Lanterne") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Lumache_pasta.jpg", "Lumache") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Lumaconi.jpg", "Lumaconi") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Mandala_pasta.jpg", "Mandala") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Orecchiette_Pasta.JPG", "Orecchiette") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Pipe_Pasta.jpg", "Pipe") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Quadrefiore.jpg", "Quadrefiore") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-EMS-Radiatore-CU-124957.JPG", "Radiatori") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Ricciolini.jpg", "Ricciolini") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Ricciutelli.jpg", "Ricciutelle") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Rotelle.jpg", "Rotelle") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Rotini.jpg", "Rotini") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/Sorprese.jpg", "Sorprese") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/Sorprese_Lisce.jpg", "Sorprese Lisce") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Strozzapreti_Pasta.JPG", "Strozzapreti") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Torchio_noodle.jpg", "Torchio") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Trofie_pasta_macro.jpg", "Trofie") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-AciniDiPepe3.jpg", "Acini di pepe") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Buchstabensuppe.jpg", "Alfabeto") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Uncooked_anellini_pasta.jpg", "Anelli") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Anellini2.jpg", "Anellini") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Conchigliette.jpg", "Conchigliette") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Corallini.jpg", "Corallini") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Ditalini.jpg", "Ditalini") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Tarhonya-3.JPG", "Egg barley") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Farfalloni.jpg", "Farfalline") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Fideo_%28coiled_vermicelli%29.JPG", "Fideos") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-UncookedFregula.jpg", "Fregula") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/Grattini.jpg", "Grattini") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/Grattoni.jpg", "Grattoni") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/Midolline.jpg", "Midolline") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Occhip.jpg", "Occhi di pernice") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Orzo.jpg", "Orzo (also, risoni)") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Pastina.jpg", "Pastina") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Pearl_Pasta.jpg", "Pearl Pasta") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/Puntine.jpg", "Puntine") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Quadrettini.jpg", "Quadrettini") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/Risi.jpg", "Risi") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Seme_melone_nudo.jpg", "Seme di melone") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Pasta_stelline.jpg", "Stelline") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Stortini_pasta.jpg", "Stortini") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Btpasta%281%29.jpg", "Tripolini") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Agnolotti.jpg", "Agnolotti") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Cannelloni_mit_Hackfleischf%C3%BCllung.jpg", "Cannelloni") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Cappelletti1.JPG", "Cappelletti") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Casoncelli_in_una_grande_padella.jpg", "Casoncelli or casonsèi") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Fagottini_al_tartufo.JPG", "Fagottini") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Maultaschensuppe.jpg", "Maultasche") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Pelmeni.jpg", "Pelmeni") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-01_Beskidische_Teigtaschen%2C_Sanok_2012.JPG", "Pierogi") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Ravioli-casalinghi-con-la-ricotta-2.jpg", "Ravioli") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Bologna-DSCF7178.JPG", "Tortellini") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Pastasorten_Tortelloni.JPG", "Tortelloni") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Gnocchi_with_truffle.jpg", "Gnocchi") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Passatelli-piato.JPG", "Passatelli") );
        list.add( new Pasta("http://gbrain.dlsi.ua.es/pastalist/120px-Sp%C3%A4tzle-02.jpg", "Spatzle") );

        return list;
    }
}
